name: handle_wait_builder
description: Handle wait bulder.
version: 0.9.0
repository: https://github.com/karbunkul/flutter_handle_wait_builder

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  dart_code_metrics: any

flutter:

